#############################################################################
# Makefile for building: practica2
# Generated by qmake (2.01a) (Qt 4.8.1) on: Fri Oct 5 16:52:32 2012
# Project:  practica2.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile practica2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Iclases -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		ventanaPrincipal.cpp \
		clases/Elipse.cpp \
		clases/lienzo.cpp \
		clases/Linea.cpp \
		clases/Polilinea.cpp \
		clases/Rectangulo.cpp \
		clases/Texto.cpp moc_ventanaPrincipal.cpp \
		moc_lienzo.cpp
OBJECTS       = main.o \
		ventanaPrincipal.o \
		Elipse.o \
		lienzo.o \
		Linea.o \
		Polilinea.o \
		Rectangulo.o \
		Texto.o \
		moc_ventanaPrincipal.o \
		moc_lienzo.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		practica2.pro
QMAKE_TARGET  = practica2
DESTDIR       = 
TARGET        = practica2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_lienzo.h ui_ventanaPrincipal.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: practica2.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -unix -o Makefile practica2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile practica2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/practica21.0.0 || $(MKDIR) .tmp/practica21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/practica21.0.0/ && $(COPY_FILE) --parents ventanaPrincipal.h clases/Elipse.h clases/Figura.h clases/lienzo.h clases/Linea.h clases/Polilinea.h clases/Rectangulo.h clases/Texto.h .tmp/practica21.0.0/ && $(COPY_FILE) --parents main.cpp ventanaPrincipal.cpp clases/Elipse.cpp clases/lienzo.cpp clases/Linea.cpp clases/Polilinea.cpp clases/Rectangulo.cpp clases/Texto.cpp .tmp/practica21.0.0/ && $(COPY_FILE) --parents ui/lienzo.ui ui/ventanaPrincipal.ui .tmp/practica21.0.0/ && (cd `dirname .tmp/practica21.0.0` && $(TAR) practica21.0.0.tar practica21.0.0 && $(COMPRESS) practica21.0.0.tar) && $(MOVE) `dirname .tmp/practica21.0.0`/practica21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/practica21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ventanaPrincipal.cpp moc_lienzo.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ventanaPrincipal.cpp moc_lienzo.cpp
moc_ventanaPrincipal.cpp: ui_ventanaPrincipal.h \
		clases/lienzo.h \
		ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h \
		ventanaPrincipal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ventanaPrincipal.h -o moc_ventanaPrincipal.cpp

moc_lienzo.cpp: ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h \
		clases/lienzo.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) clases/lienzo.h -o moc_lienzo.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_lienzo.h ui_ventanaPrincipal.h
compiler_uic_clean:
	-$(DEL_FILE) ui_lienzo.h ui_ventanaPrincipal.h
ui_lienzo.h: ui/lienzo.ui
	/usr/bin/uic-qt4 ui/lienzo.ui -o ui_lienzo.h

ui_ventanaPrincipal.h: ui/ventanaPrincipal.ui \
		clases/lienzo.h \
		ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h
	/usr/bin/uic-qt4 ui/ventanaPrincipal.ui -o ui_ventanaPrincipal.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ventanaPrincipal.h \
		ui_ventanaPrincipal.h \
		clases/lienzo.h \
		ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ventanaPrincipal.o: ventanaPrincipal.cpp ventanaPrincipal.h \
		ui_ventanaPrincipal.h \
		clases/lienzo.h \
		ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ventanaPrincipal.o ventanaPrincipal.cpp

Elipse.o: clases/Elipse.cpp clases/Figura.h \
		clases/Elipse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Elipse.o clases/Elipse.cpp

lienzo.o: clases/lienzo.cpp clases/lienzo.h \
		ui_lienzo.h \
		clases/Linea.h \
		clases/Figura.h \
		clases/Elipse.h \
		clases/Rectangulo.h \
		clases/Polilinea.h \
		clases/Texto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lienzo.o clases/lienzo.cpp

Linea.o: clases/Linea.cpp clases/Figura.h \
		clases/Linea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Linea.o clases/Linea.cpp

Polilinea.o: clases/Polilinea.cpp clases/Polilinea.h \
		clases/Figura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Polilinea.o clases/Polilinea.cpp

Rectangulo.o: clases/Rectangulo.cpp clases/Figura.h \
		clases/Rectangulo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rectangulo.o clases/Rectangulo.cpp

Texto.o: clases/Texto.cpp clases/Texto.h \
		clases/Figura.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texto.o clases/Texto.cpp

moc_ventanaPrincipal.o: moc_ventanaPrincipal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ventanaPrincipal.o moc_ventanaPrincipal.cpp

moc_lienzo.o: moc_lienzo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lienzo.o moc_lienzo.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

